//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class kolvo_materials
    {
        public int id_kolvo_mat { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<int> kolvo_mat { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual products products { get; set; }
    }
}
