//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials()
        {
            this.kolvo_materials = new HashSet<kolvo_materials>();
        }
    
        public int id_material { get; set; }
        public string naim { get; set; }
        public Nullable<int> id_type_material { get; set; }
        public Nullable<int> quantity_v_upakovke { get; set; }
        public Nullable<int> id_ed_izm { get; set; }
        public Nullable<int> quantity_na_sklade { get; set; }
        public Nullable<int> min_ostatok { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual ed_izm ed_izm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kolvo_materials> kolvo_materials { get; set; }
        public virtual type_materials type_materials { get; set; }
    }
}
