//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.kolvo_materials = new HashSet<kolvo_materials>();
        }
    
        public int id_product { get; set; }
        public string naimenovanie { get; set; }
        public string articul { get; set; }
        public Nullable<int> min_cost_for_agent { get; set; }
        public string image { get; set; }
        public Nullable<int> id_type_prod { get; set; }
        public Nullable<int> kolvo_people_for_proizv { get; set; }
        public Nullable<int> number_ceh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kolvo_materials> kolvo_materials { get; set; }
        public virtual type_products type_products { get; set; }
    }
}
